deployments:
  environment-mapping:
    development:
      - "dev"
      - "development-*"
    testing:
      - "test"
      - "*-test"
    staging:
      - "stage"
      - "pre-prod"
      - "stage2"
      - "pre-prod1"
      - "stage1"
    production:
      - "prod"
